### ISSUE TITLE
from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by imshafikul** [devcshort/react-hls#1]
I am facing a CORS error when I start streaming Url. I just confused about how to remove the problem. Can you please help over the problem?

**Comment by devcshort** [comment]
> I am facing a CORS error when I start streaming Url. I just confused about how to remove the problem. Can you please help over the problem?

This will depend on the server you are requesting the video from. If it's a server that you've created, then you will need to enable CORS on your server.
[See how to enable CORS server side](https://enable-cors.org/server.html)

If you don't have access to the server, then you will have to try enabling CORS from the client. There's no guarantee it'll work, as CORS is meant to be enabled by the server.
[See how to enable CORS client side](https://gist.github.com/jesperorb/6ca596217c8dfba237744966c2b5ab1e)
