### ISSUE TITLE
Add import statements to documentation

### ISSUE THREAD

**Issue by Emkay860** [devcshort/react-hls#15]
Documentation is simple and concise but for beginners who are new to using npm packages, it will be better to include steps on how to import the react-hls packages into their react applications

**Comment by devcshort** [comment]
Great suggestion! Thanks @Emkay860

**Comment by mrjelveh** [comment]
I really don't know how to use it,
one thing I think is necessary is a better document or example to use `hlsConfig`.

**Comment by devcshort** [comment]
@Emkay860 As of the latest version, I've added in supporting code to show the process of importing the component and then using it.

@mrjelveh I'll be adding an example of using hlsConfig in the near future. 💯
