### ISSUE TITLE
Error safari mobile does not work

### ISSUE THREAD

**Issue by andreshenao206** [devcshort/react-hls#17]
Hi, I am using react htl player and it works perfect in browsers, but in safari mobile it doesn't, I can't find the error, they know it may be the error.

```
 <ReactHlsPlayer
            url={this.state.video}
            autoplay={true}
            controls={true}
            width="100%"
            height="80%"
            className="playerppal"
            hlsConfig={{
              liveDurationInfinity:false,
              forceVideo: true,
              autoStartLoad: true,
              startPosition: -1,
              debug: false,
            }}
          />
```

Thank you

**Comment by devcshort** [comment]
@andreshenao206 currently iOS browsers do not work. Unfortunately it doesn't support the APIs that are in use by the underlying hls.js package. I'd like to get iOS support working, but at the current time, I don't have the extra time to add this functionality.

This is referenced in #13

**Comment by andreshenao206** [comment]
Ok thanks
