### ISSUE TITLE
Convert package to TypeScript

### ISSUE THREAD

**Issue by devcshort** [devcshort/react-hls#5]
Currently I have an index.d.ts file so that users of my package can take advantage of VSCode's intellisense. While this works, I'd prefer to have this package changed to use proper types, interfaces, etc and utilize TypeScript for the components within the src directory.

This change will need to take semver in to consideration, and changes will need to be fully backwards compatible with the current API. Once this change is done, I should only need to update a minor version for the next publish.

**Comment by mxrcochxvez** [comment]
Can I tackle this?

**Comment by devcshort** [comment]
@mxrcochxvez for sure!

**Comment by devcshort** [comment]
@all-contributors please add @mxrcochxvez for changing the code to typescript and being awesome!

**Comment by osmarpetry** [comment]
I already did it o. My work project, very easy today with babel to have js and ts code. I will check this out tonight
