### ISSUE TITLE
Setup Travis CI for deployment to NPM

### ISSUE THREAD

**Issue by devcshort** [devcshort/react-hls#7]
I'd like for this repo to be set up with Travis CI. It will need to run tests (once implemented), and then deploy to NPM if all tests succeed.

**Comment by soub4i** [comment]
@devcshort  What about doing this with github action it's a cleaner way.
If yes I will take this issue

**Comment by devcshort** [comment]
@AbderrahimSoubaiElidrissi I'm not familiar with github actions, but if it can accomplish the same thing then I'd be okay with that.

**Comment by officialpm** [comment]
Hey @devcshort  I am ready give a shot to this too! 🤟🏻

**Comment by rohan2734** [comment]
@devcshort  Hey i would like to work on this issue can you assign me this issue

**Comment by devcshort** [comment]
@AbderrahimSoubaiElidrissi were you still interested? Don't want to give it away if you plan to work on it

**Comment by devcshort** [comment]
@officialpm I haven't received a response from the previous person interested. Are you still interested in taking on this issue?

**Comment by officialpm** [comment]
> @officialpm I haven't received a response from the previous person interested. Are you still interested in taking on this issue?

#### Yes🤘🏻 @devcshort

**Comment by devcshort** [comment]
Going to close this for now. Will need to be tackled once we have proper tests in place.
